services:
  postgres_service:
    image: postgres
    container_name: "postgres_service"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: flight_management
    volumes:
      - pg1_data:/var/lib/postgresql/data

volumes:
  pg1_data: